# Distribution Package
[project]
name = "shared-code-lib"
version = "0.0.0"
dependencies = [
    "external-package-x>=1.2.3",
    "external-package-y>=3.2.1"
]

# Import Packages pointing to their package folders
[tool.setuptools.package-dir]
shared_code = 'src/shared_code'
